### ISSUE TITLE
Suggestion: Botany Trees

### ISSUE THREAD

**Issue by Atyneton** [TeamAOF/skylore#21]
As said in title, I request botany Trees to be added - Aegis
P. S. not sure if this is where I suggest things, but it was the first thing I found lol

**Comment by RobertasJ** [comment]
This is indeed where you suggest things

**Comment by Monster-Zer0** [comment]
https://github.com/TeamAOF/skylore/commit/7c2413048074404ca7db4b814aa05bdae0078638
