### ISSUE TITLE
backpack quests

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#30]
![image](https://user-images.githubusercontent.com/99212606/212303181-b18086ee-b868-4107-86f4-d05264f6d740.png)
you have to put in 40 lvs to unlock the blazing backpack and only then you can start unlocking the withered one, even tho they are not an upgrade of each other
maybe do smt like this?
![image](https://user-images.githubusercontent.com/99212606/212303871-e6932c8d-75a0-4445-83d6-77900ea4026a.png)

**Comment by Monster-Zer0** [comment]
good idea

**Comment by kads-e** [comment]
fyi, this not done D:

**Comment by kads-e** [comment]
or wait, it was done at some point I think, but in 2.1 its not anymore

**Comment by Monster-Zer0** [comment]
fixed in 2.2
