### ISSUE TITLE
Adding vanilla tools to the vanilla_tools_no_pickup phase results in all items/blocks using vanilla tools in crafting makes them uncraftable.

### ISSUE THREAD

**Issue by EnderReaper64** [TeamAOF/skylore#34]
I would suggest fixing this by either:
1. change the recipes of all the items/blocks used by vanilla tools to use tinkers construct tools
2. remove them from the vanilla_tools_no_pickup phase and just set the vanilla tools' durability to 0, making them unusable without breaking. Also add in a tooltip that says that they cannot be used. Removing their recipe would as I said in the title, make items/blocks using them uncraftable.

**Comment by RobertasJ** [comment]
This is probably the best fix, but i think we are planning on making vanilla tools usable but instead make tinkers just a way to get better tools.
