### ISSUE TITLE
mixed ore recipes 

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#37]
(all the recipes for mixed ore)
![image](https://user-images.githubusercontent.com/99212606/212434194-d99e1c56-b4ba-46af-b81d-12035e17e3fd.png)
maybe add some crushing wheel and mi macerator recipes where you get 50% for iron, copper and gold raw, just like normal mining, only a bit more (tho you can probably buff that by a lot, normal ores in the macerator gives 3 raw, this one 1.5 on avr)

**Comment by Monster-Zer0** [comment]
oh this is good idea
