### ISSUE TITLE
ae2 wrenches quest

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#39]
![image](https://user-images.githubusercontent.com/99212606/212435318-836106f4-0b2d-4b75-a11e-c59f822c74a0.png)
its the same one basically, maybe a make me OR make me quest, or how its called, its 4 am for me rn

**Comment by RobertasJ** [comment]
Giving myself a note to fix this tomorrow.

**Comment by Monster-Zer0** [comment]
Fixed
