### ISSUE TITLE
final tier of botany pots has no quest

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#40]
![image](https://user-images.githubusercontent.com/99212606/212447593-6ecbbaae-8c7f-4475-be93-8869a2d403d0.png)
(its called "creative botany pot", but its not rly "creative" its just fast af)
![image](https://user-images.githubusercontent.com/99212606/212447607-31e193e1-59ac-4d0c-96fa-e94bf68ba6c9.png)

**Comment by kads-e** [comment]
you can also just remove the recipe, even the elite is strong enough for most things...
oh and I would also change the 2 basically same quest with make normal then hoppery into a make this or this quest and a recipe to be able to upgrade the hoppery version, since you can only upgrade the normal version, if I dont have smt weird in my head

**Comment by RobertasJ** [comment]
We might have to remove it if it is that fast.

**Comment by kads-e** [comment]
or make it more expensive...
could reduce a lot of lag, it you decide to use biodiesel like me in aof6 (but ig the MI update isnt on 1.18 (yet(or you just didnt update?)))

**Comment by Monster-Zer0** [comment]
botany pots tiers has been removed

just regular botany pots now.
