### ISSUE TITLE
Remove Ex Nihilo and Create Sieves

### ISSUE THREAD

**Issue by falseresync** [TeamAOF/skylore#44]
Currently these two mods even with low yields allow for automated grinding of resources in quantities enough to support a multiplayer base. Additionally, even the smallest islands usually contain all of the components, required to begin the journey: trees, coal and iron. Moreover, wouldn't it be more of a struggle to exhaust your island's resources and have to venture out for more? Instead of building bigger and bigger automation chains, producing a stream of resources. Therefore I suggest to remove Ex Nihilo and sieves from the game

**Comment by Monster-Zer0** [comment]
Hmmm, they are technically already removed, except for the barrels and crooks. I removed the sieve recipes themselves, I should remove them from REI though.

I kept it in mostly for the create sifter, which I intend to make it difficult to make the meshes for.

When I say I kept ex nihlio in for create sifter, I mean I kept it in for the small parts you get from sifting.

Is all that still too much?

**Comment by RobertasJ** [comment]
no matter how much you nerf it it will always be too easy for early game.

**Comment by SirKnightBJ** [comment]
I would suggest locking things behind phase walls before getting rid of them all together. 

Also, It is my opinion that there has to be balance. The early game shouldn't be so grueling that it turns people off from the mod-pack. Making a pack an "expert pack" when Fabric isn't nearly as popular as Forge is in my opinion a mistake. It would be wise to try to lure some of the long time forge players and/or new players by making the early game as inviting and inclusive as possible. Hooking them by giving the reward of instant gratification and then reeling them in with a progressively harder mid to late game.

There's my two cents.

**Comment by Monster-Zer0** [comment]
> I would suggest locking things behind phase walls before getting rid of them all together.
> 
> Also, It is my opinion that there has to be balance. The early game shouldn't be so grueling that it turns people off from the mod-pack. Making a pack an "expert pack" when Fabric isn't nearly as popular as Forge is in my opinion a mistake. It would be wise to try to lure some of the long time forge players and/or new players by making the early game as inviting and inclusive as possible. Hooking them by giving the reward of instant gratification and then reeling them in with a progressively harder mid to late game could really pay off.
> 
> There's my two cents.

I agree with the idea of hooking then going from there.. however, unlimited resources seems to really break the game.. even if gated. I am welcome to new ideas to help kick start the pack. I can always put sieves and extractinator back if game seems to grueling without. however, those items don't reward exploring, which is kinda the main reason there are islands in the first place.

**Comment by RobertasJ** [comment]
the mid game is the part where you get to some amount of automated resources, the thing with that part is that it really makes the game a lot easier from that point on. i dont think people should be crafting forever and setting up a single miner at each dimension which brings in resources inter dimension to the main base. i would rather people set up infrastructure to get items flowing and have to maintain it once a while to keep getting the resources. if there was no reason to maintain those places it would also mean they would just be set up for a second just to do the task of getting resources.

i would suggest no real way that is easy to transport liquids or items inter dimension unless they are at the late game.
