### ISSUE TITLE
'Chipped' Recipes or there lack of

### ISSUE THREAD

**Issue by SirKnightBJ** [TeamAOF/skylore#45]
The Chipped Mod seems to have a few missing recipes. Currently all chipped Glass Panes are uncraftable and so is the Carpenter's Workbench. This could just be an REI issue. However, Aegis suggested it might be because the Workbench might have a vanilla tool in it's recipe.

**Comment by RobertasJ** [comment]
Will be fixed next update with the reintroduction of vanilla tools.

**Comment by RobertasJ** [comment]
Will be fixed next beta, you can now close this issue.
