### ISSUE TITLE
Macaw's Roofs Add Request

### ISSUE THREAD

**Issue by SirKnightBJ** [TeamAOF/skylore#46]
SketchMacaw's mods are fantastic decor mods please add all of them, especially roofs. 

https://www.curseforge.com/members/sketch_macaw/projects

Thanks!

**Comment by Nyfaria** [comment]
Maybe not bridges.. bridges can be laggy.

**Comment by SirKnightBJ** [comment]
lol bridges is already in the pack

**Comment by Nyfaria** [comment]
well then lol

**Comment by RobertasJ** [comment]
You should probably close this issue.
