### ISSUE TITLE
sort by name + assembler

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#48]
![image](https://user-images.githubusercontent.com/99212606/212503620-9aa15151-37bc-47ab-ba74-b614e9727363.png)
did not find anywhere else, but there are probably hundreds
is this even fixable?

**Comment by kads-e** [comment]
ok nvm, mixer too
but since we will hopefully have "sort" on middle mouse click next update anyways, we can just remove it, right? :D

**Comment by RobertasJ** [comment]
Has this been fixed yet?

**Comment by RobertasJ** [comment]
he is referring that the sort button is inside one of the slots he is hovering over, we need to make the button disappear but still leaving the functionality in with only the mmb being able to sort. from what i see the inventory sort mod is annoying because the button appears wherever it wants

**Comment by Monster-Zer0** [comment]
how is this not an issue in aof? it doesn't even have the device blacklisted

https://github.com/TeamAOF/All-of-Fabric-5/blob/main/config/inventorysorter/blacklist.json5

**Comment by MechanicalDragon0687** [comment]
"displaySort": false,

**Comment by RobertasJ** [comment]
#55
