### ISSUE TITLE
Handcrafted Add Request 

### ISSUE THREAD

**Issue by SirKnightBJ** [TeamAOF/skylore#50]
This Looks Incredible! 
I've been waiting for a decent decor mod for fabric for quite some time. And well, here it is!

From the creators of Chipped:
https://www.curseforge.com/minecraft/mc-mods/handcrafted/screenshots

**Comment by Monster-Zer0** [comment]
there is no 1.19 version and the old 1.0 version called home bodies doesn't work for 1.18.2

**Comment by RobertasJ** [comment]
Should probably get the label of invalid and get closed.
