### ISSUE TITLE
unification issues

### ISSUE THREAD

**Issue by RobertasJ** [TeamAOF/skylore#61]
- compat for plate cast in tinkers 
![image](https://user-images.githubusercontent.com/66907345/213269148-0e6a754a-ced7-4cf5-97da-bd98d8c2f3ae.png)
- allow indrev pulverizer to pulverize MI only ores
![image](https://user-images.githubusercontent.com/66907345/213269319-442395cc-e7c4-4035-a1aa-950e89751202.png)

**Comment by Monster-Zer0** [comment]
not going to do any compat for tinkers. AK is already working on this for AOF, also Tinkers will be replaced at some point with another mod.
