### ISSUE TITLE
rei overlaps tinkers

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/skylore#62]
![image](https://user-images.githubusercontent.com/99212606/213288890-6a37c7ec-8994-478e-83d0-79b456530ecf.png)

**Comment by Monster-Zer0** [comment]
change column width on rei.

there is a mod that is breaking the tinkers plugin. and since tinkers will not be a permanent mod, there is no use in binary searching to find it.

**Comment by kads-e** [comment]
tinkers is not a permanent mod? how do you want to replace it?
I think it fits great...

**Comment by Monster-Zer0** [comment]
there is a mod that is being developed (that I am a part of) that is going to replace it. it fits way better as well.

**Comment by kads-e** [comment]
:0
what is it (plz dont be silent gear 2.0)

**Comment by Monster-Zer0** [comment]
completely new
