### ISSUE TITLE
Enchantment Table

### ISSUE THREAD

**Issue by Stoettho** [TeamAOF/skylore#66]
Maybe I am missing something but the quest with the enchantment table is marked green but the enchantmenttable is still locked.
What am I doing wrong?

**Comment by RobertasJ** [comment]
Could you provide an image?

**Comment by Stoettho** [comment]
I hope this works out?

![Quest](https://user-images.githubusercontent.com/38001545/213885908-9fc083cc-ac51-4766-b5a4-44163f619d46.PNG)
![Table](https://user-images.githubusercontent.com/38001545/213885909-05aee534-b80a-4f0d-ae47-1079a4fe5189.PNG)

**Comment by RobertasJ** [comment]
Probably hasnt been tested, well imma see what i can do.

**Comment by Stoettho** [comment]
Thank you that worked well, hope I was the only one with that issue!

Really nice modpack between, keep up the good work!

**Comment by RobertasJ** [comment]
Its probably not just you. This quest was added a while back and im planning on changing up some parts of that chapter.

**Comment by RobertasJ** [comment]
Ok i actually have a different question, what version of the beta are you on and did you die or travel dimensions after claiming that phase?

**Comment by Stoettho** [comment]
Beta 2.2 and no dimension travel just one death but it was approx an hour after claiming.

**Comment by RobertasJ** [comment]
Huh, try dying again and see if you still are able to use it, make sure to have the item in your inv.

**Comment by Stoettho** [comment]
I granted myself the phase it works now but there is an explosion whenever u do an enchantment

**Comment by Stoettho** [comment]
and the item disappears

**Comment by RobertasJ** [comment]
Ok well at least its working now. Just remember that upgrading from each version can cause issues most of the time. Its pretty good to start over after each beta.

**Comment by Stoettho** [comment]
Yes that usually is a good idea but the progress on my current map ... but thats non of your problem ;-)
Thank you anyways for the quick feedback on this.

**Comment by RobertasJ** [comment]
You are welcome. This issue can be closed.
