### ISSUE TITLE
Gold spiked work like Diamond spikes

### ISSUE THREAD

**Issue by Stoettho** [TeamAOF/skylore#67]
Sorry to bother again but I think the gold spikes are not working correct atm.

I get the player drops with only gold spikes not jus exp.

Works good for me but there is no need to upgrade to diamond then :-)

![Spikes](https://user-images.githubusercontent.com/38001545/213886101-ff511772-b995-4789-80eb-c17f7652e9b4.PNG)

**Comment by RobertasJ** [comment]
Huh, well from what i remember the pack isnt supposed to help with mobfarms. Maybe the spikes should be removed from the game. Imma leave this to monster.

**Comment by Stoettho** [comment]
Fine for me, because of the "carry" funktion you can collect a lot of spawners with the airships ... maybe a bit to easy to farm xp and loot if you want to make the game harder then the removal is a good idea :-)

**Comment by RobertasJ** [comment]
You should reopen this issue, we close it after we resolve it.
