### ISSUE TITLE
Make Botany pots more expensive and require exploration

### ISSUE THREAD

**Issue by falseresync** [TeamAOF/skylore#69]
Botany pots are not hard to make and essentially provide players with infinite food, fuel and wood from the very first few hours of playing.
This is why I suggest to make them more expensive and use some underused resources from structures. For example, they could use in their recipe:
- Dark iron and dark iron blocks from Graveyard instead of iron and in addition to clay. Currently these resources are only used for decoration
- Gems or gem blocks from Spectrum in addition to everything else. Some gems don't have much purpose
- Vanilla materials like Bottle o'Enchanting

**Comment by Monster-Zer0** [comment]
I think this is good.. plus probably gating it behind some phases.

**Comment by falseresync** [comment]
For the first tier I'd do:
```
C.C
CPC
III
```
C terracotta, P vanilla pot, I dark iron from Graveyard

For the second tier:
```
C.C
BFB
TTT
```
C terracotta, B dark iron block,
F first tier pot, T tungsten ingot

**Comment by falseresync** [comment]
Or wait are they even multi-tiered? I can't remember
