### ISSUE TITLE
Nutrition progression locked.

### ISSUE THREAD

**Issue by w0mby** [TeamAOF/skylore#79]
version: Skylore Beta 2.2

![image](https://user-images.githubusercontent.com/5497663/215266278-fb059a56-e2b6-4484-a109-b5c2112f8ca7.png)
It seems that the progression is not possible due to the non existent knife in Croptopia (not available in rei, and no receipe when click on it from quest window)

**Comment by RobertasJ** [comment]
i wonder whats causing the recipe to not be shown in rei, as it is craftable, the recipe does seem to have this removed: true for some reason...

`"croptopia:knife": {
            "recipe": {
                "type": "minecraft:crafting_shaped",
                "pattern": [
                    " #",
                    "i "
                ],
                "key": {
                    "i": {
                        "item": "minecraft:stick"
                    },
                    "#": {
                        "tag": "c:iron_ingots"
                    }
                },
                "result": {
                    "item": "croptopia:knife"
                }
            },
            "inputs": [
                {
                    "item": "minecraft:stick"
                },
                {
                    "tag": "c:iron_ingots"
                }
            ],
            "outputs": [
                {
                    "item": "croptopia:knife",
                    "count": 1
                }
            ],
            "removed": true`

![image](https://user-images.githubusercontent.com/66907345/215266876-296c90af-651e-4291-ad98-048876ed3901.png)

which leads me to suspect it was removed by us
![image](https://user-images.githubusercontent.com/66907345/215266913-0f51bad9-6453-4f11-b084-94141ea43376.png)

and i am right, well im going to pr this as a fix soon.

**Comment by RobertasJ** [comment]
i think this should link the pr to this issue #80
